# Generated by Django 4.2.1 on 2023-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name': 'categoría de productos', 'verbose_name_plural': 'categorías de productos'},
        ),
        migrations.RemoveField(
            model_name='productocategoria',
            name='description',
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
